# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'githubUsers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for githubUsers
	pod 'SnapKit'
	pod 'Kingfisher', '~> 4.10.1'
	pod 'RxSwift'
	pod 'RxCocoa'
	
end
